---
# TODO: How to add user benchmark without specifying uris
# benchmarks:
#     - dataset: benchmark://poj104-v0
#       max_benchmarks: 5

benchmarks:
    - uris:
          - benchmark://poj104-v0/1_13
          - benchmark://poj104-v0/1_17
          - benchmark://poj104-v0/2_5
          - benchmark://poj104-v0/2_11