---
timeout_hours: 1
exploration: false
runs_per_benchmark: 1

benchmarks:
    - dataset: benchmark://hpctoolkit-cpu-v0

    - uris:
          - benchmark://hpctoolkit-cpu-v0/conv2d
          - benchmark://hpctoolkit-cpu-v0/offsets1
          - benchmark://hpctoolkit-cpu-v0/nanosleep
          - benchmark://hpctoolkit-cpu-v0/simple_pow